### ISSUE TITLE
Unable to run the indy-vdr on android

### ISSUE THREAD

**Issue by realabbas** [hyperledger/indy-vdr#193]
The app crashes at startup after installing the package.

Following logs are captured through `adb logcat`

```
05-30 16:33:20.727 30937 31063 E AndroidRuntime: Process: com.askarwallet, PID: 30937
05-30 16:33:20.727 30937 31063 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "pthread_cond_clockwait" referenced by "/data/app/com.askarwallet-2EdSrN9Tehk3NWdBlRjyng==/lib/arm64/libindy_vdr.so"...
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1667)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at org.hyperledger.indyvdr.IndyVdrModule.<clinit>(IndyVdrModule.java:23)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at org.hyperledger.indyvdr.IndyVdrPackage.createNativeModules(IndyVdrPackage.java:17)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1425)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1396)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1287)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
05-30 16:33:20.727 30937 31063 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

### Versions

```
react-native: 0.66.1
@aries-framework/indy-vdr:  ^0.4.0-alpha.127
@hyperledger/indy-vdr-react-native: ^0.1.0-dev.14
```

**Comment by TimoGlastra** [comment]
Can you try updating the indy-vdr package to dev.15? @blu3beri just released a new version that should fix this issue

**Comment by realabbas** [comment]
> Can you try updating the indy-vdr package to dev.15? @blu3beri just released a new version that should fix this issue

Sure, giving it a try

**Comment by realabbas** [comment]
> Can you try updating the indy-vdr package to dev.15? @blu3beri just released a new version that should fix this issue

Yeah thanks, it worked !
